name: Close Parent Issue When All Child Issues Are Closed

on:
  issues:
    types: [closed]
  push:
    branches:
      - main

jobs:
  check-child-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if all child issues are closed
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the current issue number (the closed issue triggering this workflow)
            const issueNumber = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            // Get the issue details to identify its parent
            const { data: issueDetails } = await github.rest.issues.get({
              owner,
              repo,
              issue_number: issueNumber,
            });

            // Assuming the parent is indicated by a label or a custom field.
            const parentIssueNumber = issueDetails.parent_id || issueDetails.labels.find(label => label.name === 'parent')?.id;

            // If no parent is found, exit early
            if (!parentIssueNumber) {
              console.log('No parent issue associated with this child.');
              return;
            }

            // Get all issues in the repo
            const { data: issues } = await github.rest.issues.listForRepo({
              owner,
              repo,
            });

            // Filter out the child issues by label, or a custom parent-child relationship (for example using labels)
            const childIssues = issues.filter(issue => issue.parent_id === parentIssueNumber || issue.labels.some(label => label.name === 'child'));

            // Check if all child issues are closed
            const allClosed = childIssues.every(issue => issue.state === 'closed');

            if (allClosed) {
              // Close the parent issue if all child issues are closed
              await github.rest.issues.update({
                owner,
                repo,
                issue_number: parentIssueNumber,
                state: 'closed'
              });
            }
